compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  tensor-hq:
    npmAlwaysAuth: true
    npmAuthToken: "${GH_AUTH_TOKEN:-}"
    npmPublishRegistry: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.3.0.cjs
